In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#data1='/content/drive/MyDrive/Book1.xlsx'

In [ ]:
#data1

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
import pandas as pd
import numpy as np

# Assuming your dataset is named "data" and is a pandas DataFrame
# Replace 'data' with the actual variable holding your dataset
random_data='/content/drive/MyDrive/random_data_2.xlsx'
data = pd.read_excel(random_data)
# Extract features and target variable
X = data.drop(columns=["Result"])  # Features
y = data["Result"]  # Target label

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Decision Tree Classifier
clf = DecisionTreeClassifier()

# Train the model on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
# Calculate and display the confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.99
Confusion Matrix:
[[177   1]
 [  1  21]]


***2.Naive Bayes Algo***

In [ ]:
from sklearn.naive_bayes import GaussianNB
# Create a Gaussian Naive Bayes Classifier
clf = GaussianNB()

# Train the model on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate and display the confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Calculate and display the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Confusion Matrix:
[[177   1]
 [  1  21]]
Accuracy: 0.99


3.Gradient Bosting Algo

In [ ]:


import xgboost as xgb
# Create an XGBoost classifier
clf = xgb.XGBClassifier()

# Train the model on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate and display the confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Calculate and display the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Confusion Matrix:
[[177   1]
 [  1  21]]
Accuracy: 0.99


**4.SVMS Algo**

In [ ]:
from sklearn.svm import SVC
# Create an SVM classifier (SVC)
clf = SVC()

# Train the model on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate and display the confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Calculate and display the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Confusion Matrix:
[[177   1]
 [  1  21]]
Accuracy: 0.99


**5.Logistic Regression**

In [ ]:



from sklearn.linear_model import LogisticRegression
# Create a Logistic Regression model
clf = LogisticRegression()

# Train the model on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate and display the confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Calculate and display the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Confusion Matrix:
[[177   1]
 [  1  21]]
Accuracy: 0.99
